### ISSUE TITLE
How to extend ScalaResolver?

### ISSUE THREAD

**Issue by arteme** [sfxcode/pebble-scala#35]
Hi,

Thank you so much for this project. I've struggle so much to get jinja-like templates with first-class scala support. `ScalaResolver` works well for a variety of basic data types, but if one wishes to extend it or substitute their own, it is surprisingly difficult to do.

If one were able to supply a different instance of `ScalaExtension` when instantiating `ScalaPebbleEngine`, it would be way easier.

**Comment by arteme** [comment]
Another point to add: `ScalaPebbleEngine`, `ScalaExtension` and `ScalaResolver` are all case classes. In scala 3 case-to-case inheritance is prohibited, which means that they are de-facto non-extensible.

**Comment by sfxcode** [comment]
Hi,

you can overwrite the ScalaExtension with the latest version.

ScalaExtension and ScalaResolver are no case classes anymore.
Usage:

```scala
  val Engine: ScalaPebbleEngine = ScalaPebbleEngine()
  Engine.scalaExtension = new MyScalaExtension(globalContext = Map("info" -> BuildInfo))
```

Hope that help,

Greetings Tom

**Comment by arteme** [comment]
Thank you so much for such prompt fixes!
