### ISSUE TITLE
`ScalaPebbleEngine` disregards `PebbleBuilder` from `getBuilder`

### ISSUE THREAD

**Issue by arteme** [sfxcode/pebble-scala#37]
Hi again,

While case-to-case inheritance is scala 3 is a problem for extending the `pebble-scala` classes on class level (as I mentioned in #35), one can still override things on instance level:
```
def customEngine() =
  new ScalaPebbleEngine(useStringLoader = true) {
    override def getBuilder: PebbleEngine.Buider = ???
  }
```

So it seems one would be able to provide a custom builder, but `getEngine` uses the private builder (`engine = Some(PebbleBuilder.build())`) so the effort of overriding just the `getBuilder` method is futile. Granted, `getBuilder` is designed to configure the pebble engine, not to replace the builder altogether, but if `getEngine` always used the builder provided `getBuilder`, it would be easy to do both.

**Comment by sfxcode** [comment]
should be obsolet with https://github.com/sfxcode/pebble-scala/issues/35
